apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-guard
  namespace: ctrl-prompt
  labels:
    app: llm-guard
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef: # the claimRef is here to provide a "connection" between this pv and the pvc.
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: llm-guard
    namespace: ctrl-prompt
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data/
