---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llm-guard
  namespace: ctrl-prompt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: llm-guard
  namespace: ctrl-prompt
  labels:
    app: llm-guard
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: llm-guard
    namespace: ctrl-prompt
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data/
